### PR TITLE
resolves #55

### LINKED ISSUE #55: Not Responsive
The mobile view of Recipes doesn't have the navbar at all, and the elements are positioned haphardly.

### PR DESCRIPTION
**Pull request by sb39**

### CODE REVIEW

**Comment by MattCSmith** [comment]
@sb39 
There's a minor conflict is this one, probably due to the PR pending before yours. Could you resolve or let me know which one to keep. Thanks ;)

**Comment by sb39** [comment]
@MattCSmith  wait a minute I think the issue is unresolved

**Comment by MattCSmith** [comment]
@sb39 Let me know when you are ready for me to merge it

**Comment by sb39** [comment]
fixed #55

**Pull request merged**
