### PR TITLE
figuring out how to do pull request without conflicts

### PR DESCRIPTION
**Pull request by peacebefore**
added recipes, book summaries

### CODE REVIEW

**Comment by peacebefore** [comment]
I'm not sure how to resolve the conflict. I was trying to do it through Github but it says I need write access to the repository. In my terminal when I follow the instructions for syncing a fork using git upstream etc, it says I'm already up to date. I'm confused on how to get to the conflicting information so that I can fix it for the pull request.

**Comment by SamirJouni** [comment]
Hey, 
There are conflict markers in the conflicting files. They look like this: 

>>>>>>>> somebranch 

=============

>>>>>>>> someotherbranch

You need to compare them, and see how you can fix the conflict that is happening between the markers. Once fixed, you can delete the markers and push to your fork. 

Good Luck ! :)

**Comment by MattCSmith** [comment]
Hey @peacebefore,
If you reach out to me on Discord, I might be able to help you solve the conflict
Regards
Matt

**Comment by peacebefore** [comment]
I did it!!! Thanks, Matt and Samir!

**Pull request merged**
